version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  node:
    build: .
    container_name: node-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: "mongodb://mongo:27017/testdb"
    volumes:
      - ./src:/usr/src/app/src

volumes:
  mongo-data: